/**
 * Title: about.component.ts
 * Author: Devan Wong
 * Date: 8 January 2020
 * Description: About component page
 */

import { Component, OnInit } from '@angular/core';
// This was autogenerated but its declaring what the component will have.
@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
