/**
 * Title: wishlist.component.ts
 * Author: Devan Wong
 * Date: 4 February 2021
 * Description: Wishlist component
 */
// This was autogenerated
import { Component, OnInit } from '@angular/core';
// Importing IWishlist-item interface
import { IWishlistItem } from '../wishlist-item.interface';
// This was autogenerated
@Component({
  selector: 'app-wishlist',
  templateUrl: './wishlist.component.html',
  styleUrls: ['./wishlist.component.scss']
})
export class WishlistComponent implements OnInit {
  // Creating a form field inside the component setting it to an empty array.
  items: Array<IWishlistItem> = [];

  constructor() { }

  ngOnInit(): void {
  }
  // Create a function to update the items
  updateItemsHandler(item: IWishlistItem) {
    // The handler is taking a new wishlist item and push that object to the items array
    this.items.push(item)
  }
}
