/*
============================================
; Title: Exercise 4.3 - Handling Events with Observables
; Author: Devan Wong
; Date: 23 January 2021
; Description: This is the app.module.ts page
;===========================================
*/
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
// These are importing all components and app routing page. These are autogenerated.
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { ContactComponent } from './contact/contact.component';
import { AboutComponent } from './about/about.component';
import { ComposerListComponent } from './composer-list/composer-list.component';
import { ComposerDetailsComponent } from './composer-details/composer-details.component';
// importing the router module page because it is how we are going to be able to pass data to our module file
// import { RouterModule } from '@angular/router';
// importing form modules and reactive forms from built in angular
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

// The imports and declared to the ngmodule, most are autogenerated
@NgModule({
  declarations: [
    AppComponent,
    ComposerListComponent,
    ContactComponent,
    AboutComponent,
    ComposerDetailsComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    // RouterModule,
    FormsModule,
    ReactiveFormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
