/**
 * Title: home.component.ts
 * Author: Devan Wong
 * Date: 5 February 2021
 * Description: home component
 */
// This was autogenerated
// We have not made any edits to this page yet.

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
