/**
 * Title: contact.component.ts
 * Author: Devan Wong
 * Date: 8 January 2020
 * Description: Contact component page
 */

import { Component, OnInit } from '@angular/core';
// This was autogenerated but its declaring what the component will have.
@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css']
})
// This is a class
export class ContactComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
