/**
 * Title: composer-list.component.ts
 * Author: Devan Wong
 * Date: 25 January 2020
 * Description: Composer List page, this will display a list of composers
 */

import { Component, OnInit } from '@angular/core';
// adding to import the Icomposer Interface
import { IComposer } from '../composer.interface';
// adding to import the Composer service
import { ComposerService } from '../composer.service';
// This was autogenerated but its declaring what the component will have.
@Component({
  selector: 'app-composer-list',
  templateUrl: './composer-list.component.html',
  styleUrls: ['./composer-list.component.css']
})

export class ComposerListComponent implements OnInit {
// This is creating a composer property called composers and its going to have an array of IComposer. This is a local component variable
composers: Array<IComposer>;
  constructor(private composerService: ComposerService) {
    //This is dependency injection that is a built in feature of angular
    this.composers = this.composerService.getComposers();
   }
  ngOnInit(): void {
  }

}
