/**
 * Title: base-layout.component.ts
 * Author: Devan Wong
 * Date: 5 February 2021
 * Description: baselayout component
 */
// This was autogenerated
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-base-layout',
  templateUrl: './base-layout.component.html',
  styleUrls: ['./base-layout.component.css']
})
export class BaseLayoutComponent implements OnInit {
  // This is to define the variable in the html file.
  assignment: string;

  constructor() {
    // This is assigned to the current exercise we are using
    this.assignment = 'Assignment 6.4 - Input Properties';
  }

  ngOnInit(): void {
  }

}
