/**
 * Title: app.component.ts
 * Author: Devan Wong
 * Date: 8 January 2021
 * Description: App component
 */

import { Component } from '@angular/core';
// This was autogenerated but its declaring what the component will have.
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
// This is where the variable is defined. Variable can be found in the in the app.component.html page
export class AppComponent {
  assignment: string = 'Exercise 3.3 - Passing Data to Routes, Part 2';
}
