/**
 * Title: auth-layout.component.ts
 * Author: Devan Wong
 * Date: 5 February 2021
 * Description: auth-layout component
 */
// This was autogenerated
// We have not made any edits to this page yet.
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-auth-layout',
  templateUrl: './auth-layout.component.html',
  styleUrls: ['./auth-layout.component.css']
})
export class AuthLayoutComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
