/**
 * Title: base-layout.component.ts
 * Author: Devan Wong
 * Date: 10 February 2021
 * Description: baselayout component
 */
// This was autogenerated
import { Component, OnInit } from '@angular/core';
// Importing cookie service
import { CookieService } from 'ngx-cookie-service';
// Importing the router
import { Router } from '@angular/router';
@Component({
  selector: 'app-base-layout',
  templateUrl: './base-layout.component.html',
  styleUrls: ['./base-layout.component.css']
})
export class BaseLayoutComponent implements OnInit {
  // This is to define the variable in the html file.
  assignment: string;
  // adding cookie service to the constructor to be referenced.
  constructor(private cookieService: CookieService, private router: Router) {
    // This is assigned to the current exercise we are using
    this.assignment = 'GPA Calculator';
  }

  ngOnInit(): void {
  }
  // Creating a function to sign out once the user is signed in -- link will be at the top.
  signOut() {
    //  calling the cookie service to delete all entries inside of the cooke inside the browser. -- call the delete all function with the cookie service .
    this.cookieService.deleteAll();
    // navigate to the signin page.
    this.router.navigate(['/session/sign-in']);
   }
}
