/*
============================================
; Title: Exercise 3.2 - Enhance Composer App
; Author: Devan Wong
; Date: 15 January 2021
; Description: This is the app.component.ts page
;===========================================
*/
// This page has be autopopulated
import { Component } from '@angular/core';
// This was autogenerated but its declaring what the component will have.
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
// The title has been updated to the current assignment.
export class AppComponent {
  assignment: string = 'Exercise 4.2 - Inversion of Control and Dependency Injection';
}
