/**
 * Title: home.component.ts
 * Author: Devan Wong
 * Date: 11 February 2021
 * Description: home component
 */
// This was autogenerated
import { Component, OnInit } from '@angular/core';
// This is importing the transcript interface.
import { ITranscript } from '../transcript.interface';
// Importing forms & validators
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  // Adding a variable to set the default values grades
  selectableGrades: Array<string> = ['A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-', 'F'];
  // Adding a variable to set to an empty array
  transcriptEntries: Array<ITranscript> = [];
  // GPA total is get to 0
  // This is the parent component class.
  gpaTotal: number = 0;
  // Adding variable for the form group.
  transcriptForm: FormGroup;
  // Added private form builder.
  constructor(private fb: FormBuilder) {
  }

  ngOnInit(): void {
    // This is building new form groups with form controls requiring validators on the course and grade.
    this.transcriptForm = this.fb.group({
      course: ['', Validators.required ],
      grade: ['', Validators.required]
    });
  }
  // This returns the transcript form
  get form() {
    return this.transcriptForm.controls
  }
  // Function created to push inputs from grade entry to be displayed on the transcript.
  onSubmit(event) {
    // This is to push a new obj literal to the transcript entries
    this.transcriptEntries.push(
      {
      course: this.form.course.value,
      grade: this.form.grade.value
     }
    )
    // This will reset validations
    event.currentTarget.reset();
  }
  // This is calculations to get you gpa.
  calculateResults(){
    // This is a local variable.
    let gpa: number = 0;
    // These are used to find the GPA.
    for (let entry of this.transcriptEntries) {
      console.log(entry.grade)
      switch(entry.grade) {
        case 'A':
          console.log('its an A')
          gpa += 4.0;
          break;
        case 'A-':
          console.log('its an A-')
          gpa += 3.7;
          break;
        case 'B+':
          console.log('its an B+')
          gpa += 3.33;
          break;
        case 'B':
          console.log('its an B')
          gpa += 3.00;
          break;
        case 'B-':
            console.log('its an B-')
            gpa += 2.70;
            break;
        case 'C+':
          console.log('its an C+')
          gpa += 2.30;
          break;
        case 'C':
          console.log('its an C')
          gpa += 2.00;
          break;
        case 'C-':
          console.log('its a C-')
          gpa += 1.70;
          break;
        case 'D+':
          console.log('its an D+')
          gpa += 1.30;
          break;
        case 'D':
            console.log('its an D')
            gpa += 1.0;
            break;
        case 'D-':
          console.log('its an D-')
          gpa += 0.70;
          break;
        default:
          console.log('default value')
          gpa += 0.00;
          break;
      }
    }
    // assigning to find the GPA total
    this.gpaTotal = gpa / this.transcriptEntries.length;
  }
  // This is to reset the calculations and trascripts.
  clearEntries(){
    this.transcriptEntries = [];
    this.gpaTotal = 0;
  }
}
