/**
 * Title: not-found.component.ts
 * Author: Devan Wong
 * Date: 5 February 2021
 * Description: not-found component
 */
// This was autogenerated
// We have not made any edits to this page yet.
// This is a child component
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-not-found',
  templateUrl: './not-found.component.html',
  styleUrls: ['./not-found.component.css']
})
export class NotFoundComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
