/**
 * Title: composer-list.component.ts
 * Author: Devan Wong
 * Date: 8 January 2020
 * Description: Composer List page, this will display a list of composers
 */

import { Component, OnInit } from '@angular/core';
// adding to import the Icomposer Interface
import { IComposer } from '../composer.interface';
// adding to import the Composer Class
import { Composer } from '../composer.class';
// This was autogenerated but its declaring what the component will have.
@Component({
  selector: 'app-composer-list',
  templateUrl: './composer-list.component.html',
  styleUrls: ['./composer-list.component.css']
})

export class ComposerListComponent implements OnInit {
// This is creating a composer property called composers and its going to have an array of IComposer. This is a local component variable
composers: Array<IComposer>;
  constructor() {
    //Creating a new instance of the composer class [in the composer.class.ts file]
    //getComposers returns a list of all of the contents of the this.composers array
    this.composers = new Composer().getComposers();
   }
  ngOnInit(): void {
  }

}
