/**
 * Title: grade-summary.component.ts
 * Author: Devan Wong
 * Date: 5 February 2021
 * Description: grade summary component
 */
// This was autogenerated
// Added the input property
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-grade-summary',
  templateUrl: './grade-summary.component.html',
  styleUrls: ['./grade-summary.component.css']
})
export class GradeSummaryComponent implements OnInit {
  // This is so the parents can talk to the child components.
  @Input() grade: string;
  @Input() course: string;
  constructor() { }

  ngOnInit(): void {
  }

}
