/**
 * Title: app.component.ts
 * Author: Devan Wong
 * Date: 5 February 2021
 * Description: App component
 */

// This was autogenerated
// We have not made any edits to this page yet.
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

}
