/**
 * Title: wishlist-create.component.ts
 * Author: Devan Wong
 * Date: 4 February 2021
 * Description: Wishlist Create component
 */
// This was autogenerated
// added the Event emitter and output to import
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
// This is an import statement from wishlist-item
import { IWishlistItem } from '../wishlist-item.interface';
// This was autogenerated
@Component({
  selector: 'app-wishlist-create',
  templateUrl: './wishlist-create.component.html',
  styleUrls: ['./wishlist-create.component.scss']
})


export class WishlistCreateComponent implements OnInit {
  // Create an output property that creates a new event emitter
  @Output() addItemEmitter = new EventEmitter<IWishlistItem>();
  // creating a field of an item
  item: IWishlistItem;
  constructor() {
    // instant a new wish-item and set it to the type this.item
    // casting the object literal to the object type iwishlist
    this.item = {} as IWishlistItem;
  }

  ngOnInit(): void {
  }
  // new function is to allows for users to add a wish-list item to the component
  addItem(){
    this.addItemEmitter.emit({
      title: this.item.title,
      authors: this.item.authors
    })
    // This resets the object literal to empty one the item is emitted.
    this.item = {} as IWishlistItem
  }
}
