/*
============================================
; Title: Exercise 3.3 - secure-profile-app
; Author: Devan Wong
; Date: 15 January 2021
; Description: This is the sign-on.component.ts page
;===========================================
*/
import { Component, OnInit } from '@angular/core';
//This is to import the router from angulars built in router module.
import { Router } from '@angular/router';
// This was autogenerated but its declaring what the component will have.
@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.css']
})
export class SignInComponent implements OnInit {
  isLoggedIn = false;
  // Inside the parentheses is the Router from being imported
  constructor(private router: Router) { }

  ngOnInit(): void {
  }
  // This is connect to the sign in button in the sign-in component html. This gives the button a behavior.
  signin(){
    // This is to implement the isLoggedIn Logic
    this.isLoggedIn = true;
    // This will navigate the page to the homeComponent
    //isLoggedIn corresponds to the home.component this.route.snapshot.queryParamMap.get('isLoggedIn')
    // this.router.navigate navigates to another page.
    // Query parameters in Angular allow for passing optional parameters across any route in the application. This what you might want to achieve if you looking for authorization or authentication in an angular project.
    // skipLocationChange [default to false] can change the route, without changing the URL in the browser.
    this.router.navigate(['/home'], {queryParams: {isLoggedIn: this.isLoggedIn}, skipLocationChange: true});
  }
}
