/**
 * Title: my-image.components.ts
 * Author: Devan Wong
 * Date: 8 January 2020
 * Description: my-image.components
 */

import { Component, OnInit } from '@angular/core';
// This was autogenerated but its declaring what the component will have.
@Component({
  selector: 'app-my-image',
  templateUrl: './my-image.component.html',
  styleUrls: ['./my-image.component.css']
})
export class MyImageComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
